---
- name: Configure Application
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Install Git
      apt: 
        name: git
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - git:
        repo: 'https://bitbucket.org/azneita/devops-challenge.git'
        dest: /opt/
        force: true

    - name: Installing modules from requirment file.
      pip:
        requirements: /opt/requirements.txt
        executable: pip3
     
    - name: Installing gunicorn module    
      pip:
        name: gunicorn
        executable: pip3

    - name: Run webapp script!
      command: gunicorn app:app -D -b 0.0.0.0:5000 --chdir=/opt/
      run_once: true

